let a = 2

try {
    allert("cx")
    
} catch (error) {
    console.log(error)
}